import { createHash, createPrivateKey, sign, timingSafeEqual } from "node:crypto";
import { NextResponse } from "next/server";

export type LicenseType =
  | "evaluation"
  | "solo"
  | "professional"
  | "team"
  | "enterprise";

const licenseTypes = ["solo", "professional", "team", "enterprise"];

// Mints v2 signed keys: `rowsncolumns.<base64url payload>.<base64url ECDSA
// P-256 signature>`. The payload (id, licensee, type, end) is covered by the
// signature; @rowsncolumns/spreadsheet verifies it offline against the
// embedded public key. `end` is the version cutoff (perpetual license with a
// one-year update window).
//
// Env:
//   LICENSE_SIGNING_KEY — PKCS8 PEM private key, either verbatim or base64
//     encoded (generated by spreadsheet's scripts/license-keygen.mjs).
//   LICENSE_API_TOKEN — shared secret; callers pass it as a Bearer token or
//     a `token` query param.

const getSigningKey = () => {
  const raw = process.env.LICENSE_SIGNING_KEY;
  if (!raw) {
    return undefined;
  }
  const pem = raw.includes("-----BEGIN")
    ? raw
    : Buffer.from(raw, "base64").toString("utf8");
  return createPrivateKey(pem);
};

const isAuthorized = (request: Request, url: URL) => {
  const expected = process.env.LICENSE_API_TOKEN;
  if (!expected) {
    return false;
  }
  const provided =
    request.headers.get("authorization")?.replace(/^Bearer\s+/i, "") ??
    url.searchParams.get("token");
  if (!provided) {
    return false;
  }
  // Hash both sides so timingSafeEqual gets equal-length buffers.
  return timingSafeEqual(
    createHash("sha256").update(provided).digest(),
    createHash("sha256").update(expected).digest()
  );
};

const generateLicenseCode = (
  userId: string,
  licenseType: LicenseType,
  licensee: string
) => {
  const key = getSigningKey();
  if (!key) {
    return undefined;
  }
  const startDate = new Date().toISOString().split("T")[0];
  const startDateObj = new Date(startDate);
  startDateObj.setFullYear(startDateObj.getFullYear() + 1);
  const end = startDateObj.toISOString().split("T")[0];

  const payload = Buffer.from(
    JSON.stringify({ id: userId, licensee, type: licenseType, end })
  );
  // WebCrypto verifies ECDSA in IEEE P1363 (r||s) form, not DER.
  const signature = sign("sha256", payload, {
    key,
    dsaEncoding: "ieee-p1363",
  });
  return `rowsncolumns.${payload.toString("base64url")}.${signature.toString(
    "base64url"
  )}`;
};

export async function GET(request: Request) {
  const url = new URL(request.url);
  if (!isAuthorized(request, url)) {
    return NextResponse.json({}, { status: 401 });
  }
  const userId = url.searchParams.get("userId");
  const licenseType = url.searchParams.get("licenseType") as LicenseType;
  const licensee = url.searchParams.get("licensee") ?? userId;
  if (!userId || !licensee || !licenseTypes.includes(licenseType)) {
    return NextResponse.json({}, { status: 404 });
  }
  const license = generateLicenseCode(userId, licenseType, licensee);
  if (!license) {
    return NextResponse.json(
      { error: "LICENSE_SIGNING_KEY is not configured" },
      { status: 500 }
    );
  }
  return NextResponse.json({ license });
}
